version: '3'

services:
  nats-server:
    container_name: nats-server
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    container_name: client-gateway
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./client-gateway/.env
    depends_on:
      - nats-server

  auth-ms:
    container_name: auth-ms
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./auth-ms/.env
    depends_on:
      - nats-server
      - auth-db

  products-ms:
    container_name: products-ms
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./products-ms/.env
    depends_on:
      - nats-server

  orders-ms:
    container_name: orders-ms
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./orders-ms/.env
    depends_on:
      - nats-server
      - orders-db

  payments-ms:
    container_name: payments-ms
    build: ./payments-ms
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: npm run start:dev
    env_file:
      - ./payments-ms/.env
    depends_on:
      - nats-server
  
  orders-db:
    container_name: orders-db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./orders-db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ordersdb
  
  auth-db:
    container_name: auth-db
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - "27017:27017"
    volumes:
      - ./auth-db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example1234
      MONGO_INITDB_DATABASE: authdb
      # ME_CONFIG_MONGODB_URL: mongodb://root:example1234@auth-db:27017
    
