apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: danielcaamal97/payments-ms
          name: payments-ms
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
            - name: STRIPE_SUCCESS_URL
              value: "http://localhost:3000/api/v1/payments/success"
            - name: STRIPE_CANCEL_URL
              value: "http://localhost:3000/api/v1/payments/cancel"
            - name: STRIPE_SECRET_KEY
              value: "sk_test_51J3J9eK"
            - name: STRIPE_WEBHOOK_SECRET
              value: "whsec_51J3J9eK"
          resources: {}
status: {}
